---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\Control\Director:
  alternate_base_url: '`SS_BASE_URL`'
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'default'
    - '$default'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - app/css/cms.css
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'https://use.typekit.net/gpv2hcx.css'
    - 'themes/default/dist/css/editor.css'
SilverStripe\Core\Injector\Injector:
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }
SilverStripe\Security\Member:
  extensions:
    - App\Extensions\Security\MemberExtension
SilverStripe\Security\MemberAuthenticator\LostPasswordHandler:
  extensions:
    - App\Extensions\Security\LostPasswordHandler
