---
Name: app-security
Before:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: 'App\Security\MemberAuthenticator\MemberLoginForm'
