.live: &live
  hostname: '__HOSTNAME__'
  user: '__USER__'

.staging: &staging
  hostname: '159.65.28.17'
  user: 'fiberlean'

.defaults: &defaults
  repository: 'git@github.com:bigfork/fiberlean.git'
  deploy_path: '~/public_html'
  roles:
    - 'app'

production:
  <<: *live
  <<: *defaults
  stage: production
prod:
  <<: *live
  <<: *defaults
  stage: production
live:
  <<: *live
  <<: *defaults
  stage: production

staging:
  <<: *staging
  <<: *defaults
  stage: staging
stage:
  <<: *staging
  <<: *defaults
  stage: staging
test:
  <<: *staging
  <<: *defaults
  stage: staging
